'use client';

import { type CSSProperties, useEffect, useState } from 'react';
import Link from 'next/link';
import { ClipboardCheck, ExternalLink, ShieldCheck, UsersRound } from 'lucide-react';
import { apiService } from '@/services/apiService';

type Assignment = { id: string; network_id: string; network_name: string; program_name?: string; role: string; resource_type: 'INITIATIVE' | 'DOCUMENT' | 'PROJECT'; resource_id: string; permission: string; expires_at?: string | null; initiative_title?: string; initiative_stage?: string; next_review_at?: string | null };
const tone: Record<string, string> = { MENTOR: '#60a5fa', EVALUATOR: '#c084fc', SPONSOR: '#fbbf24', PARTNER: '#4ade80', REQUESTER: '#94a3b8' };

export default function NetworkAssignmentsPage() {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { apiService.get<{ assignments: Assignment[] }>('/api/networks/assignments', true).then((r) => { if (r.success && r.data) setAssignments(r.data.assignments); }).finally(() => setLoading(false)); }, []);
  return <main style={page}><header style={header}><div><p style={eyebrow}>COLABORACIÓN EXTERNA</p><h1 style={title}>Mis asignaciones de red</h1><p style={subtitle}>Aquí sólo aparecen los recursos que una organización te concedió explícitamente. No tienes acceso al resto de su workspace.</p></div><Link href="/dashboard/initiatives" style={link}><ClipboardCheck size={16}/> Mis iniciativas internas</Link></header><section style={notice}><ShieldCheck size={18}/><span>Los accesos pueden expirar o revocarse en cualquier momento. Cada apertura queda registrada por la red.</span></section>{loading ? <div style={empty}>Cargando asignaciones…</div> : assignments.length === 0 ? <div style={empty}><UsersRound size={28}/><strong>No tienes asignaciones externas activas.</strong><span>Cuando aceptes una invitación de mentor, evaluador o aliado, aparecerá aquí.</span></div> : <section style={grid}>{assignments.map((a) => <article key={a.id} style={card}><div style={top}><span style={{ ...badge, color: tone[a.role] ?? '#94a3b8', borderColor: `${tone[a.role] ?? '#94a3b8'}66` }}>{a.role}</span><span style={{ color: '#94a3b8', fontSize: 12 }}>{a.permission}</span></div><h2 style={{ margin: '4px 0 6px', fontSize: 18 }}>{a.initiative_title ?? `${a.resource_type.toLowerCase()} asignado`}</h2><p style={{ color: '#aab5c9', fontSize: 13, minHeight: 38 }}>{a.network_name}{a.program_name ? ` - ${a.program_name}` : ''}</p><dl style={meta}><div><dt>Revisión</dt><dd>{a.next_review_at ? new Date(a.next_review_at).toLocaleDateString('es-CL') : 'Según programa'}</dd></div><div><dt>Acceso</dt><dd>{a.expires_at ? `Hasta ${new Date(a.expires_at).toLocaleDateString('es-CL')}` : 'Vigente'}</dd></div></dl>{a.resource_type === 'INITIATIVE' && <Link href={`/dashboard/initiatives?initiative=${a.resource_id}`} style={open}>Abrir evidencia y feedback <ExternalLink size={15}/></Link>}</article>)}</section>}</main>;
}
const page: CSSProperties = { minHeight:'100%', background:'#12172a', color:'#f8fafc', padding:'40px clamp(20px,4vw,64px)', fontFamily:"'Manrope',system-ui,sans-serif" }; const header: CSSProperties={display:'flex',justifyContent:'space-between',gap:20,alignItems:'end',flexWrap:'wrap',marginBottom:22}; const eyebrow: CSSProperties={margin:0,color:'#f97316',fontSize:11,fontWeight:800,letterSpacing:'.1em'}; const title:CSSProperties={fontSize:'clamp(30px,4vw,44px)',letterSpacing:'-.05em',margin:'5px 0 8px'}; const subtitle:CSSProperties={margin:0,color:'#aab5c9',maxWidth:650,lineHeight:1.55}; const link:CSSProperties={display:'inline-flex',alignItems:'center',gap:8,textDecoration:'none',border:'1px solid #39445f',padding:'10px 13px',borderRadius:9,color:'#e7edf8',fontWeight:700}; const notice:CSSProperties={display:'flex',gap:10,alignItems:'center',background:'#19213a',border:'1px solid #314361',borderRadius:10,padding:'13px 16px',color:'#cbd5e1',fontSize:13,marginBottom:20}; const grid:CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:14}; const card:CSSProperties={border:'1px solid #2d3752',background:'#181e33',padding:17,borderRadius:12}; const top:CSSProperties={display:'flex',justifyContent:'space-between'}; const badge:CSSProperties={border:'1px solid',borderRadius:16,padding:'4px 8px',fontWeight:800,fontSize:11}; const meta:CSSProperties={display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,color:'#9eabc1',fontSize:12}; const open:CSSProperties={display:'inline-flex',gap:7,alignItems:'center',marginTop:18,color:'#f7b38f',fontWeight:800,fontSize:12,textDecoration:'none'}; const empty:CSSProperties={minHeight:230,border:'1px dashed #3a4561',borderRadius:12,display:'grid',placeItems:'center',alignContent:'center',gap:8,color:'#aab5c9',textAlign:'center'};
