'use client';

import '../styles/globals.css';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect } from 'react';
import { useIsAuthenticated } from '@/stores/authStore';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { HydrationBoundary } from '@/components/HydrationBoundary';
import { ThemeProvider } from '@/providers/ThemeProvider';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Suprimir errores de extensiones del navegador
  useEffect(() => {
    const originalError = console.error;
    console.error = (...args) => {
      // Filtrar errores de extensiones del navegador
      const errorMessage = args[0]?.toString() || '';
      if (
        errorMessage.includes('disconnected port') ||
        errorMessage.includes('Extension context invalidated')
      ) {
        return; // Ignorar estos errores
      }
      originalError.apply(console, args);
    };

    return () => {
      console.error = originalError;
    };
  }, []);
  const pathname = usePathname();
  const isAuthenticated = useIsAuthenticated();

  // No mostrar navegación en páginas de auth o dashboard (tienen su propio layout)
  const hideNav =
    pathname === '/login' || pathname === '/register' || pathname?.startsWith('/dashboard');

  return (
    <html lang="es">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes"
        />
        <meta name="theme-color" content="#3B82F6" />
        <meta
          name="description"
          content="AETHER - Event-driven collaboration platform for teams. Manage workspaces, boards, and documents in real-time."
        />
        <meta name="application-name" content="Aether" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Aether" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />

        {/* PWA Manifest */}
        <link rel="manifest" href="/manifest.json" />

        {/* Favicons */}
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="192x192" href="/icons/icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/icons/icon-512x512.png" />

        {/* Apple Touch Icons */}
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/icons/icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icons/icon-192x192.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="/icons/icon-192x192.png" />

        {/* iOS Splash Screens - Generated by PWA */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-2048-2732.png"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1668-2388.png"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1536-2048.png"
          media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1125-2436.png"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1242-2688.png"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-828-1792.png"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1242-2208.png"
          media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-750-1334.png"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-640-1136.png"
          media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />

        <title>AETHER - Collaboration Platform</title>
      </head>
      <body>
        <ErrorBoundary>
          <ThemeProvider defaultTheme="dark">
            <HydrationBoundary>
              {/* Navigation Bar */}
              {!hideNav && (
                <nav className="fixed top-0 left-0 right-0 z-50 bg-surface/95 backdrop-blur-sm border-b border-border safe-area-top">
                  <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex items-center justify-between h-14 sm:h-16">
                      {/* Logo */}
                      <Link
                        href="/"
                        className="flex items-center gap-2 text-accent hover:text-accent-hover transition-colors touch-target-lg"
                      >
                        <span className="text-lg sm:text-xl font-bold font-mono">[ AETHER ]</span>
                      </Link>

                      {/* Navigation Links */}
                      <div className="flex items-center gap-2 sm:gap-4">
                        {isAuthenticated ? (
                          <Link
                            href="/dashboard"
                            className="px-3 sm:px-5 py-2 bg-blue-600 text-white rounded-md font-medium text-xs sm:text-sm hover:bg-blue-700 transition-colors touch-target"
                          >
                            <span className="hidden xs:inline">Dashboard</span>
                            <span className="xs:hidden">Panel</span>
                          </Link>
                        ) : (
                          <>
                            <Link
                              href="/login"
                              className="px-3 sm:px-4 py-2 text-xs sm:text-sm font-medium text-text-primary hover:text-accent transition-colors touch-target"
                            >
                              <span className="hidden sm:inline">Iniciar Sesión</span>
                              <span className="sm:hidden">Login</span>
                            </Link>
                            <Link
                              href="/register"
                              className="px-3 sm:px-4 py-2 bg-accent hover:bg-accent-hover text-white rounded-lg font-semibold transition-all duration-300 text-xs sm:text-sm touch-target"
                            >
                              <span className="hidden sm:inline">Crear Cuenta</span>
                              <span className="sm:hidden">Registro</span>
                            </Link>
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                </nav>
              )}

              {/* Main Content */}
              <main className={hideNav ? '' : 'pt-14 sm:pt-16'}>{children}</main>
            </HydrationBoundary>
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
